- name: Setup and Deploy to EC2 VM
  run: |
    ssh ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
      # Install Docker and git if not present
      if ! command -v docker &> /dev/null; then
        sudo apt update
        sudo apt install -y docker.io docker-compose git
      fi

      docker -v
      docker-compose -v

      # Clone repo if not present
      if [ ! -d "~/n8n-hbrm" ]; then
        git clone https://github.com/aravindan888/n8n-hbrm ~/n8n-hbrm
      fi

      cd ~/n8n-hbrm
      git pull origin main

      docker-compose -f docker/docker-compose.yml down
      docker-compose -f docker/docker-compose.yml up -d --build
    EOF
