name: Setup Server

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: Install Docker and Git, then clone repo
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            # Install Docker & Git if missing
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io git
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            # Clone repo if not already cloned
            if [ ! -d "~/n8n-hbrm" ]; then
              git clone https://github.com/aravindan888/n8n-hbrm ~/n8n-hbrm
            else
              cd ~/n8n-hbrm && git pull origin main
            fi
          EOF
