name: Setup Server

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (on GitHub side)
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: Install Docker and Git, then clone or pull repo
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io git
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            if [ -d "$HOME/n8n-hbrm/.git" ]; then
              echo "Repo exists. Pulling latest changes..."
              cd ~/n8n-hbrm && git pull origin main
            else
              echo "Cloning repo..."
              git clone https://github.com/aravindan888/n8n-hbrm ~/n8n-hbrm
            fi
          EOF
