name: Setup Server

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            set -e

            # Remove broken Docker sources if any
            sudo rm -f /etc/apt/sources.list.d/docker.list

            # Install Docker and Compose v2
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl gnupg lsb-release

            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg

            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
            https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

            # Clone repo if not already present
            if [ ! -d "$HOME/n8n-hbrm/.git" ]; then
              git clone https://github.com/aravindan888/n8n-hbrm $HOME/n8n-hbrm
            fi

            cd $HOME/n8n-hbrm
            git pull origin main

            # Build and run services
            docker compose -f docker/docker-compose.yml down || true
            docker compose -f docker/docker-compose.yml up -d --build
          EOF
