name: Deploy n8n to VM

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 VM
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            # Clone repo if not present
            if [ ! -d "~/n8n-hbrm" ]; then
              git clone https://github.com/${{ github.repository }} ~/n8n-hbrm
            fi

            cd ~/n8n-hbrm
            git pull origin main

            docker compose -f docker/docker-compose.yml down
            docker compose -f docker/docker-compose.yml up -d --build
          EOF
