name: Setup Server

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: SSH and Setup Docker
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            # Install Docker and git
            sudo apt update
            sudo apt install -y docker.io git

            # Start and enable Docker
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER

            # Clone the repo if needed
            if [ ! -d "~/n8n-hbrm" ]; then
              git clone https://github.com/aravindan888/n8n-hbrm ~/n8n-hbrm
            fi
          EOF
